Bryce/metric processor improvements
open-telemetry/opentelemetry-swift pull request #199
Opened 2021-06-07 22:59 UTC by bryce-b

This PR fixes a retention loop between MetricProviderSdk & PushMetricController, and also fixes the resulting crash by using a DispatchSourceTimer to clean up the dispatched thread when the PushMetricController is released.

2021-06-08 07:01 UTC, nachoBonafonte commented on Sources/OpenTelemetrySdk/Metrics/Export/PushMetricController.swift
> +                let values = self.meterProvider.getMeters().values
```suggestion
                let values = meterProvider.getMeters().values
```

2021-06-08 07:01 UTC, nachoBonafonte commented on Sources/OpenTelemetrySdk/Metrics/Export/PushMetricController.swift
> +                guard let self = self else {
```suggestion
                guard let self = self,
                      let meterProvider = self.meterProvider else {
```
Here we retain meterProvider by storing in a local variable so we can read all values without potential deletion

2021-06-08 07:01 UTC, nachoBonafonte commented on Sources/OpenTelemetrySdk/Metrics/Export/PushMetricController.swift
> +    unowned var meterProvider: MeterProviderSdk
```suggestion
    weak var meterProvider: MeterProviderSdk?
```
Being unowned meterProvider could be destroyed while reading the values and the app would crash, being `weak` allows us to retain the instance in the timer event

2021-06-08 07:05 UTC, nachoBonafonte requested changes
Hi Bryce, your changes look very good, and the approach using the timer is very good. I only can see an issue with a potential crash when accessing the unowned variable. I have added suggestions so that the problem wont happen, it implies using a weak var instead of unowned and retaining in the timer event. What do you think?

2021-06-08 17:05 UTC, bryce-b commented
Looks good @nachoBonafonte ! Thanks for corrections!

2021-06-09 08:45 UTC, nachoBonafonte approved these changes

2021-06-09 08:45 UTC, merged