Use String key for tracerProvider dictionary
open-telemetry/opentelemetry-swift pull request #337
Opened 2022-10-20 18:28 UTC by mattxw

We encountered some crash regarding InstrumentationLibraryInfo that mutated during runtime. 

```
Crashed: com.alipay.plus.iapservicecommoninterceptor
0  libswiftCore.dylib             0x1125c _assertionFailure(_:_:flags:) + 248
1  libswiftCore.dylib             0x12f8e0 KEY_TYPE_OF_DICTIONARY_VIOLATES_HASHABLE_REQUIREMENTS(_:) + 2604
2  Skywalker                      0x1868300 specialized _NativeDictionary.mutatingFind(_:isUnique:) + 3301816
3  Skywalker                      0x18624ac TracerProviderSdk.get(instrumentationName:instrumentationVersion:) + 3277668 (<compiler-generated>:3277668)
4  Skywalker                      0x186835c protocol witness for TracerProvider.get(instrumentationName:instrumentationVersion:) in conformance TracerProviderSdk + 3301908 (<compiler-generated>:3301908)
```
We tried to make the property inside InstrumentationLibraryInfo as immutable, but the crash still happen. Our latest fix is to change dictionary key in `TracerProviderSdk.tracerProvider` into String type. So far, this crash does not happen anymore in our app with this fix.

2022-10-21 07:53 UTC, nachoBonafonte commented
Hi @mattxw, I am not sure this is the proper fix for the issue. InstrumentationScopeInfo is an struct so it should not mutate during time and in the way it is implemented only in the initializer. 

How are you using it?, do you have a reproducible example for the issue?, could it be showing another unrelated error which is writing out of bonds memory and affecting it? Have you run your code with  Thread sanitizer or any other sanitizer?

Thanks a lot

2022-10-21 07:55 UTC, nachoBonafonte requested changes
I am not sure this is the proper fix for the issue. InstrumentationScopeInfo is an struct so it should not mutate during time and in the way it is implemented only in the initializer.

How are you using it?, do you have a reproducible example for the issue?, could it be showing another unrelated error which is writing out of bonds memory and affecting it? Have you run your code with Thread sanitizer or any other sanitizer?

2022-10-21 12:52 UTC, mattxw commented
> I am not sure this is the proper fix for the issue. InstrumentationScopeInfo is an struct so it should not mutate during time and in the way it is implemented only in the initializer.
> 
> How are you using it?, do you have a reproducible example for the issue?, could it be showing another unrelated error which is writing out of bonds memory and affecting it? Have you run your code with Thread sanitizer or any other sanitizer?

Thanks for the response. We can't reproduce the crash, as we found it from Firebase Crashlytics. We are using [Splunk](https://github.com/signalfx/splunk-otel-ios/) that use OpenTelemetry library for observability.

I checked some of the crash session and there's one iPhone 8 Plus user with 400MB+ RAM free, so I think that wasn't out of bounds memory. We tried to change InstrumentationScopeInfo property to immutable (`let` instead of `var`), but the crash still happen. 

We haven't tried Thread Sanitizer though, since this solution fixed the crash in our current release.

2022-10-21 13:31 UTC, nachoBonafonte commented
Hi, InstrumentationScopeInfo is an struct and inmutable once initialised, being the properties let or var should not make a difference. 

As I said, I don't think this is the solution, and I think it's just hiding the real issue, which is probably a concurrent access to the Dictionary and that `Thread Sanitizer` should show even when not crashing.

On this [PR](https://github.com/open-telemetry/opentelemetry-swift/pull/306) a race condition was fixed that was related to the access of that dictionary. The PR was merged 27-Jun-2022, any release from the library after that [1.1.4 ](https://github.com/open-telemetry/opentelemetry-swift/releases/tag/1.1.4) and newer, should have it fixed. 

Please check with version of opentelemetry-swift is being used by the version of the Splunk you are linking, if its older than 1.1.4, then your crash is probably already fixed. If it's newer than it,then it means that there is another thread race condition that `Thread Sanitizer` should warn about and that we can fix when we know where it happens.

2022-10-24 14:56 UTC, mattxw commented
Hi, @nachoBonafonte. Thanks for the advice, I tried your suggestion to check Thread Sanitizer to reproduce the crash stack trace, but there was no warning regarding OpenTelemetry. I also tried the latest version of OpenTelemetry and it has an access race on TracerProviderSdk. 

```
==================
WARNING: ThreadSanitizer: Swift access race (pid=4090)
  Modifying access of Swift variable at 0x7b3c00001d20 by thread T16:
	#0 TracerProviderSdk.get(instrumentationName:instrumentationVersion:) <null>:2 (App:x86_64+0x1035e17dd)
	#1 protocol witness for TracerProvider.get(instrumentationName:instrumentationVersion:) in conformance TracerProviderSdk <null>:2 (App:x86_64+0x1035e3027)
	#2 buildTracer() <null>:2 (App:x86_64+0x103410b12)
    #3 static SplunkRum.log(name:type:parent:) <null>:2 (App:x86_64+0x103413136)
	#4 SplunkService.trackOperation(_:) SplunkService.swift:83 (App:x86_64+0x101c2960f)
	#5 protocol witness for SplunkServiceable.trackOperation(_:) in conformance SplunkService <compiler-generated> (App:x86_64+0x101c2c91d)
	#6 SplunkSubInterceptor.afterRpcOperation(_:) SplunkInterceptor.swift:69 (App:x86_64+0x102acb92d)
	#7 SplunkInterceptor.afterRpcOperation(_:) SplunkInterceptor.swift:46 (App:x86_64+0x102acb00a)
	#8 @objc SplunkInterceptor.afterRpcOperation(_:) <compiler-generated> (App:x86_64+0x102acb9ef)
	#9 __49-[MainInterceptor afterRpcOperation:]_block_invoke <null>:2 (App:x86_64+0x105d7bc6f)
	#10 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x4a5a)
	#11 -[MainInterceptor afterRpcOperation:] <null>:2 (App:x86_64+0x105d7ba6c)
	#12 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x4a5a)

  Previous modifying access of Swift variable at 0x7b3c00001d20 by thread T27 (mutexes: write M898603468670800912):
	#0 TracerProviderSdk.get(instrumentationName:instrumentationVersion:) <null>:2 (App:x86_64+0x1035e17dd)
	#1 protocol witness for TracerProvider.get(instrumentationName:instrumentationVersion:) in conformance TracerProviderSdk <null>:2 (App:x86_64+0x1035e3027)
	#2 buildTracer() <null>:2 (App:x86_64+0x103410b12)
	#3 startHttpSpan(request:) <null>:2 (App:x86_64+0x103423cb4)
	#4 SessionTaskObserver.observeValue(forKeyPath:of:change:context:) <null>:2 (App:x86_64+0x103425978)
	#5 @objc SessionTaskObserver.observeValue(forKeyPath:of:change:context:) <null>:2 (App:x86_64+0x1034262b4)
	#6 NSKeyValueNotifyObserver <null>:2 (Foundation:x86_64+0xb126d)
	#7 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x4a5a)
```
Regardless, I don't think it is related, as we also implemented NSRecursiveLock on the dictionary before. Do you have any other suggestion for this crash? Or maybe a suggestion to make this solution proper? Thanks before.

2022-10-24 15:03 UTC, nachoBonafonte commented
Could you provide the thread sanitizer error symbolicated? If running on debug and with debug symbols generated, Thread Sanitizer will show the file and line of the offending access. 

What are the exact versions you are using, both opentelemetry-swift and the splunk library?

2022-10-24 15:33 UTC, nachoBonafonte commented
Can you show where are the accesses? Clicking on the left view in each of the mutating accesses

2022-10-24 17:19 UTC, mattxw commented
Both thread have similar stack trace, but here's what I can show for the 2nd and 3rd stack.

![Screen Shot 2022-10-25 at 00 17 41](https://user-images.githubusercontent.com/10057596/197586832-37030ccc-5e85-4cde-9bee-7bdb46cbe62a.png)
![Screen Shot 2022-10-25 at 00 17 14](https://user-images.githubusercontent.com/10057596/197586854-5c370ebf-6c5d-43eb-b144-34995333831e.png)

2022-10-27 09:12 UTC, nachoBonafonte commented
Sorry I think I was not clear enough, I want to know where are the accesses being done in the library, so the stack line 0 of the mutating acces by thread 84 and by thread 20

2022-11-03 16:56 UTC, mattxw commented
Hey, @nachoBonafonte, sorry for being MIA. Here's the access mentioned by Xcode. It's the same part of library that I posted weeks ago.

![Screenshot 2022-11-03 at 23 54 38](https://user-images.githubusercontent.com/10057596/199785236-6aa91bad-f681-4f88-ba64-6800a0e3e98c.png)

![Screenshot 2022-11-03 at 23 54 27](https://user-images.githubusercontent.com/10057596/199785207-e7600dab-bede-49ae-87ed-5cd757c41760.png)

2022-11-03 17:41 UTC, nachoBonafonte commented
That the offending line is the one that access the lock is very suspicious, are you sure you are not linking OpenTelemetry-swift twice? Maybe Splunk library is linking it statically inside and you are linking it again? It should show some linking warning if that is happening.

I will try to create a test that exercise this code concurrently and check if some thread sanitizer message appears.

2022-11-04 02:19 UTC, mattxw commented
> That the offending line is the one that access the lock is very suspicious, are you sure you are not linking OpenTelemetry-swift twice? Maybe Splunk library is linking it statically inside and you are linking it again? It should show some linking warning if that is happening.
> 
> I will try to create a test that exercise this code concurrently and check if some thread sanitizer message appears.

I don't think that's the case. I can only find Splunk on my linked libraries list. 🤔 

Anyway, I don't think the cause of this crash (on the first post) is access race/race condition as we also put `NSRecursiveLock` to access the dictionary before. I've tried to run thread sanitizer with our old branch and there are no warning on concurrent access anymore. Please let me know if there's something I can do for this. 🙏🏼

2023-06-01 08:03 UTC, closed without merging