added event.data nested support
open-telemetry/opentelemetry-swift pull request #431
Opened 2023-06-20 21:08 UTC by bryce-b

This PR adds support for the `event.data` nested attributes.

2023-06-21 07:54 UTC, lunij requested changes

2023-06-21 07:54 UTC, lunij commented on Sources/Exporters/Jaeger/Adapter.swift
>      }
Please respect the indentation being used in this project.

2023-06-29 15:44 UTC, nachoBonafonte approved these changes

2023-06-29 15:46 UTC, merged

2024-02-14 10:59 UTC, crsantos commented
Hello, 

I need help trying to understand what use cases we have for this nested attribute.

**Context:**

* I have noticed that there are platforms that do not handle this level of deep
* I have bumped into this because I was wrongly using it to surface `ios.state` as `event.data` ([see Mobile conventions](https://opentelemetry.io/docs/specs/semconv/mobile/events/#ios))
* But I was able to see the event being correctly reported because switched to [setAttributes](https://github.com/open-telemetry/opentelemetry-swift/blob/0033445b1de9516c16b75d678b0003a8b5ec1c8b/Sources/OpenTelemetrySdk/Logs/LogRecordBuilderSdk.swift#L61-L64)

I would like to understand what makes sense to be `event.data` or a regular attribute.