Expands LogRecord to allow "anyValue" in body parameter.
open-telemetry/opentelemetry-swift pull request #499
Opened 2023-12-20 22:11 UTC by bryce-b

2023-12-20 23:32 UTC, vvydier commented
That looks like the right way to do it!  I created the spec-change branch after I modified the ActivityContextManager code and test case in my main, so it also shows up here. Do you think it would be ok to merge this or do we need to remove the ActivityContextManager updates from this PR?

2023-12-21 04:26 UTC, vvydier approved these changes
Looks good to me!

2023-12-21 16:50 UTC, nachoBonafonte requested changes
LGTM, but there are some changes that I think are part of another PR from @vvydier

2023-12-21 16:50 UTC, nachoBonafonte commented on Sources/OpenTelemetryApi/Context/ActivityContextManager.swift
> +            contextMap[activityKey] = nil
These changes don't look related to this PR

2023-12-21 16:50 UTC, nachoBonafonte commented on Tests/OpenTelemetryApiTests/Context/ActivityContextManagerTests.swift
> +
this also looks like code not related to these changes

2023-12-21 18:20 UTC, nachoBonafonte approved these changes

2023-12-21 19:20 UTC, merged