Implement Exponential Histgoram metrics
open-telemetry/opentelemetry-swift pull request #525
Opened 2024-03-11 21:24 UTC by jhoongo

This PR implements `ExponentialHistogram` metric in Swift SDK. Most of the implementations was inspired and driven by https://github.com/open-telemetry/opentelemetry-java SDK. It has been validated with Java SDK to ensure that it generates the same results and passes the same tests for the most part.

There might be some missing area that I might have missed on this, but this should be good enough for us to starting point for supporting Exponential Histogram. 

I have excluded the implementation of Exponential Histogram on the old metric and only implemented it for Stable Metrics.

Note: I just notice the spacing/indentation issue on this PR, will follow up shortly on this.

2024-03-21 17:53 UTC, nachoBonafonte requested changes
Really great work, just some minor stylistic issues.

2024-03-21 17:53 UTC, nachoBonafonte commented on Sources/OpenTelemetrySdk/Metrics/Stable/Aggregation/AdaptingCircularBufferCounter.swift
> +    private static let NULL_INDEX: Int = Int.min
Please use Swift style names even  for constants (no capitals and no underscore even for constants. If you want something more visual maybe you can wrap it in an enum like:
```
 enum Index {
 case null = -1
}
```
And use it like `public private(set) var endIndex = Index.null`

2024-03-21 17:53 UTC, nachoBonafonte commented on Sources/OpenTelemetrySdk/Metrics/Stable/Aggregation/AdaptingCircularBufferCounter.swift
> +        if self.baseIndex == Int.min {
Avoid using self when not needed (e.g. an init when the parameters matches the name )

2024-03-21 17:53 UTC, nachoBonafonte commented on Sources/OpenTelemetrySdk/Metrics/Stable/Data/Internal/Base2ExponentialHistogramIndexer.swift
> +    private static let LOG_BASE2_E = 1.0 / log(2)
same as before with constant names

2024-03-21 17:53 UTC, nachoBonafonte commented on Sources/OpenTelemetrySdk/Metrics/Stable/Data/Internal/ExponentialHistogramPointData.swift
> +    public init(scale: Int, sum: Double, zeroCount: Int64, hasMin: Bool, hasMax: Bool, min: Double, max: Double, positiveBuckets: ExponentialHistogramBuckets, negativeBuckets: ExponentialHistogramBuc
use one parameter per line for these kind of long functions

2024-03-21 23:06 UTC, jhoongo commented
> Really great work, just some minor stylistic issues.

Thanks for the review @nachoBonafonte ! I've updated the PR with your feedback and rebase it to the latest main. Please let me know if you still have any further feedback or concern. Thanks,

2024-03-23 07:50 UTC, nachoBonafonte approved these changes

2024-03-23 07:50 UTC, merged