added other AV task exceptions in NSURLSession instrumentation
open-telemetry/opentelemetry-swift pull request #640
Opened 2024-11-21 16:49 UTC by bryce-b

There are additional AV download tasks that need to be accounted for. 
Related issues : https://github.com/elastic/apm-agent-ios/issues/242

2024-11-21 17:04 UTC, batuhansk requested changes
It would be nice to use the

2024-11-21 17:04 UTC, batuhansk commented on Sources/Instrumentation/URLSession/URLSessionInstrumentation.swift
> +        for aClass in Self.AVTaskClassList {
`contains(where:)` would be more idiomatic.

`guard !Self.AVTaskClassList.contains(where: { task.isKind(of: $0) }) else { return }`

2024-11-21 17:04 UTC, batuhansk commented on Sources/Instrumentation/URLSession/URLSessionInstrumentation.swift
> +    var classes : [AnyClass] = []
```swift
let classes = names.compactMap { NSClassFromString($0) }
return classes
```

2024-11-21 17:18 UTC, vvydier approved these changes

2024-11-22 11:22 UTC, batuhansk approved these changes

2024-11-22 11:33 UTC, nachoBonafonte approved these changes

2024-11-22 13:41 UTC, merged