enabled swiftlint & fixed issues
open-telemetry/opentelemetry-swift pull request #657
Opened 2024-12-14 00:29 UTC by bryce-b

I've added the swiftlint plugin to the 5.9 package.swift. I've also added .swiftlint and disabled several rules that are less simple to resolve, that we may revisit in the future.

2024-12-14 00:30 UTC, bryce-b commented
It looks like I'll need to review swiftlint & the github actions. I'll investigate this in the new year.

2024-12-16 13:25 UTC, ArielDemarco commented
My 2 cents on the swiftlint usage: If the primary consumer of `OpenTelemetry-Swift` also uses SwiftLint, you’re likely to encounter many integration issues if they're using SPM.
Beyond the fact that when you download a dependency with SPM, it pulls in all its dependencies (meaning `SwiftLint` would also be downloaded in this case), one of the main issues with `SwiftLint` is that, aside from being heavy as a dependency, it’s also **_not stable and introduces many breaking changes from version to version_** (you can check on [their releases](https://github.com/realm/SwiftLint/releases) they even include a `Breaking` changes section)

As a result, I believe this will cause significant integration conflicts for OpenTelemetry with many apps due to SwiftLint's instability and how unfriendly SPM is when handling heavy dependencies (Sadly, I speak from experience).

What I'd do is find other ways to enforce Swiftlint rules without exposing Swiftlint as a plugin in the `Package.swift`, either with a pre-commit hook (which could also `--fix`/`--autocorrect` issues) or other CI tooling.

2025-01-09 21:51 UTC, bryce-b commented
@ArielDemarco I really like being able to use swiftlint in xcode, and I think I've come up with a solution!
Using an env-var when loading xcode to enable it, it will not show up in the dependencies for consumers of our package, and it will not conflict with consumers that also use swiftlint.

2025-01-09 22:06 UTC, ArielDemarco commented
Looks great! I'll give it a try on a sample project but seems it'll work just fine!

2025-01-16 14:30 UTC, nachoBonafonte requested changes
Just a pair of details in the package files

2025-01-16 14:30 UTC, nachoBonafonte commented on Package.swift
> +        .library(name: " -experimental", type: .static, targets: ["OpenTracingShim"]),
This looks like an unwanted change

2025-01-16 14:30 UTC, nachoBonafonte commented on Package@swift-5.9.swift
> +//        .package(url: "https://github.com/SimplyDanny/SwiftLintPlugins", from: "0.57.1")
This also should be removed

2025-01-16 17:08 UTC, nachoBonafonte approved these changes

2025-01-16 17:52 UTC, merged